version: 0.2
env:
  variables:
    APP_NAME: "aws-code-build-sample"
    BUCKET_NAME: "frontend-deployement-poc"
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo install process started
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - ng build
  post_build:
    commands:
      - echo build process finished, we should uplload to S3 now
      - cd dist/$APP_NAME
      - ls -la
      - aws s3 sync . s3://$BUCKET_NAME --delete --cache-control max-age=300